export enum TestID {
  TIMER_BOTTOM_DISPLAY = 'TIMER_BOTTOM_DISPLAY',
  TIMER_TIME_DISPLAY = 'TIMER_TIME_DISPLAY',
  TIMER_PLAY_PAUSE_BUTTON = 'TIMER_PLAY_PAUSE_BUTTON',
  TIMER_PLAY_ICON = 'TIMER_PLAY_ICON',
  TIMER_PAUSE_ICON = 'TIMER_PAUSE_ICON',
  TIMER_RESET_ICON = 'TIMER_RESET_ICON',

  DISPLAY_BLOCK_COUNTER = 'DISPLAY_BLOCK_COUNTER',
  DISPLAY_BLOCK_LABEL = 'DISPLAY_BLOCK_LABEL',
}

