export enum TestID {
  TIMER_BOTTOM_DISPLAY = 'TIMER_BOTTOM_DISPLAY',
  TIMER_TIME_DISPLAY = 'TIMER_TIME_DISPLAY',
  TIMER_PLAY_PAUSE_BUTTON = 'TIMER_PLAY_PAUSE_BUTTON',
  TIMER_PLAY_ICON = 'TIMER_PLAY_ICON',
  TIMER_PAUSE_ICON = 'TIMER_PAUSE_ICON',
  TIMER_RESET_ICON = 'TIMER_RESET_ICON',

  DISPLAY_BLOCK_COUNTER = 'DISPLAY_BLOCK_COUNTER',
  DISPLAY_BLOCK_LABEL = 'DISPLAY_BLOCK_LABEL',

  SETTINGS_BUTTON = 'SETTINGS_BUTTON',
  SETTINGS_MODAL = 'SETTINGS_MODAL',
  SETTINGS_MODAL_WORK_TIMER = 'SETTINGS_MODAL_WORK_TIMER',
  SETTINGS_MODAL_REST_TIMER = 'SETTINGS_MODAL_REST_TIMER',
  SETTINGS_MODAL_LONG_REST_TIMER = 'SETTINGS_MODAL_LONG_REST_TIMER',

  HEADER_TITLE = 'HEADER_TITLE',

  NOTIFICATION_MODAL = 'NOTIFICATION_MODAL',
  CONFIRM_BUTTON = 'CONFIRM_BUTTON',
  RESET_BUTTON = 'RESET_BUTTON',
}

