export enum TestID {
  TIMER_BOTTOM_DISPLAY = 'TIMER_BOTTOM_DISPLAY',
  TIMER_TIME_DISPLAY = 'TIMER_TIME_DISPLAY',
  TIMER_PLAY_PAUSE_BUTTON = 'TIMER_PLAY_PAUSE_BUTTON',
  TIMER_PLAY_ICON = 'TIMER_PLAY_ICON',
  TIMER_PAUSE_ICON = 'TIMER_PAUSE_ICON',
}

